/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppPersonalRouteImport } from './routes/_app/personal'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as AppFriendsIndexRouteImport } from './routes/_app/friends/index'
import { Route as AppFriendsFriendIdRouteImport } from './routes/_app/friends/$friendId'
import { Route as AppGroupsIndexRouteImport } from './routes/_app/groups/index'
import { Route as AppGroupsGroupIdRouteImport } from './routes/_app/groups/$groupId'
import { Route as AppGroupsNewRouteImport } from './routes/_app/groups/new'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AppGroupsGroupIdIndexRouteImport } from './routes/_app/groups/$groupId/index'
import { Route as AppGroupsGroupIdInsightsRouteImport } from './routes/_app/groups/$groupId/insights'
import { Route as AppGroupsGroupIdExpensesNewRouteImport } from './routes/_app/groups/$groupId/expenses/new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppPersonalRoute = AppPersonalRouteImport.update({
  id: '/personal',
  path: '/personal',
  getParentRoute: () => AppRoute,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const AppFriendsIndexRoute = AppFriendsIndexRouteImport.update({
  id: '/friends/',
  path: '/friends/',
  getParentRoute: () => AppRoute,
} as any)
const AppFriendsFriendIdRoute = AppFriendsFriendIdRouteImport.update({
  id: '/friends/$friendId',
  path: '/friends/$friendId',
  getParentRoute: () => AppRoute,
} as any)
const AppGroupsIndexRoute = AppGroupsIndexRouteImport.update({
  id: '/groups/',
  path: '/groups/',
  getParentRoute: () => AppRoute,
} as any)
const AppGroupsGroupIdRoute = AppGroupsGroupIdRouteImport.update({
  id: '/groups/$groupId',
  path: '/groups/$groupId',
  getParentRoute: () => AppRoute,
} as any)
const AppGroupsNewRoute = AppGroupsNewRouteImport.update({
  id: '/groups/new',
  path: '/groups/new',
  getParentRoute: () => AppRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppGroupsGroupIdIndexRoute = AppGroupsGroupIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppGroupsGroupIdRoute,
} as any)
const AppGroupsGroupIdInsightsRoute =
  AppGroupsGroupIdInsightsRouteImport.update({
    id: '/insights',
    path: '/insights',
    getParentRoute: () => AppGroupsGroupIdRoute,
  } as any)
const AppGroupsGroupIdExpensesNewRoute =
  AppGroupsGroupIdExpensesNewRouteImport.update({
    id: '/expenses/new',
    path: '/expenses/new',
    getParentRoute: () => AppGroupsGroupIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/dashboard': typeof AppDashboardRoute
  '/personal': typeof AppPersonalRoute
  '/api/health': typeof ApiHealthRoute
  '/friends/$friendId': typeof AppFriendsFriendIdRoute
  '/groups/$groupId': typeof AppGroupsGroupIdRouteWithChildren
  '/groups/new': typeof AppGroupsNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/friends/': typeof AppFriendsIndexRoute
  '/groups/': typeof AppGroupsIndexRoute
  '/groups/$groupId/insights': typeof AppGroupsGroupIdInsightsRoute
  '/groups/$groupId/': typeof AppGroupsGroupIdIndexRoute
  '/groups/$groupId/expenses/new': typeof AppGroupsGroupIdExpensesNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/dashboard': typeof AppDashboardRoute
  '/personal': typeof AppPersonalRoute
  '/api/health': typeof ApiHealthRoute
  '/friends/$friendId': typeof AppFriendsFriendIdRoute
  '/groups/new': typeof AppGroupsNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/friends': typeof AppFriendsIndexRoute
  '/groups': typeof AppGroupsIndexRoute
  '/groups/$groupId/insights': typeof AppGroupsGroupIdInsightsRoute
  '/groups/$groupId': typeof AppGroupsGroupIdIndexRoute
  '/groups/$groupId/expenses/new': typeof AppGroupsGroupIdExpensesNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/settings': typeof SettingsRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/personal': typeof AppPersonalRoute
  '/api/health': typeof ApiHealthRoute
  '/_app/friends/$friendId': typeof AppFriendsFriendIdRoute
  '/_app/groups/$groupId': typeof AppGroupsGroupIdRouteWithChildren
  '/_app/groups/new': typeof AppGroupsNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_app/friends/': typeof AppFriendsIndexRoute
  '/_app/groups/': typeof AppGroupsIndexRoute
  '/_app/groups/$groupId/insights': typeof AppGroupsGroupIdInsightsRoute
  '/_app/groups/$groupId/': typeof AppGroupsGroupIdIndexRoute
  '/_app/groups/$groupId/expenses/new': typeof AppGroupsGroupIdExpensesNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/dashboard'
    | '/personal'
    | '/api/health'
    | '/friends/$friendId'
    | '/groups/$groupId'
    | '/groups/new'
    | '/api/auth/$'
    | '/friends/'
    | '/groups/'
    | '/groups/$groupId/insights'
    | '/groups/$groupId/'
    | '/groups/$groupId/expenses/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/settings'
    | '/dashboard'
    | '/personal'
    | '/api/health'
    | '/friends/$friendId'
    | '/groups/new'
    | '/api/auth/$'
    | '/friends'
    | '/groups'
    | '/groups/$groupId/insights'
    | '/groups/$groupId'
    | '/groups/$groupId/expenses/new'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/settings'
    | '/_app/dashboard'
    | '/_app/personal'
    | '/api/health'
    | '/_app/friends/$friendId'
    | '/_app/groups/$groupId'
    | '/_app/groups/new'
    | '/api/auth/$'
    | '/_app/friends/'
    | '/_app/groups/'
    | '/_app/groups/$groupId/insights'
    | '/_app/groups/$groupId/'
    | '/_app/groups/$groupId/expenses/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  SettingsRoute: typeof SettingsRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/personal': {
      id: '/_app/personal'
      path: '/personal'
      fullPath: '/personal'
      preLoaderRoute: typeof AppPersonalRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/friends/': {
      id: '/_app/friends/'
      path: '/friends'
      fullPath: '/friends/'
      preLoaderRoute: typeof AppFriendsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/friends/$friendId': {
      id: '/_app/friends/$friendId'
      path: '/friends/$friendId'
      fullPath: '/friends/$friendId'
      preLoaderRoute: typeof AppFriendsFriendIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/groups/': {
      id: '/_app/groups/'
      path: '/groups'
      fullPath: '/groups/'
      preLoaderRoute: typeof AppGroupsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/groups/$groupId': {
      id: '/_app/groups/$groupId'
      path: '/groups/$groupId'
      fullPath: '/groups/$groupId'
      preLoaderRoute: typeof AppGroupsGroupIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/groups/new': {
      id: '/_app/groups/new'
      path: '/groups/new'
      fullPath: '/groups/new'
      preLoaderRoute: typeof AppGroupsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/groups/$groupId/': {
      id: '/_app/groups/$groupId/'
      path: '/'
      fullPath: '/groups/$groupId/'
      preLoaderRoute: typeof AppGroupsGroupIdIndexRouteImport
      parentRoute: typeof AppGroupsGroupIdRoute
    }
    '/_app/groups/$groupId/insights': {
      id: '/_app/groups/$groupId/insights'
      path: '/insights'
      fullPath: '/groups/$groupId/insights'
      preLoaderRoute: typeof AppGroupsGroupIdInsightsRouteImport
      parentRoute: typeof AppGroupsGroupIdRoute
    }
    '/_app/groups/$groupId/expenses/new': {
      id: '/_app/groups/$groupId/expenses/new'
      path: '/expenses/new'
      fullPath: '/groups/$groupId/expenses/new'
      preLoaderRoute: typeof AppGroupsGroupIdExpensesNewRouteImport
      parentRoute: typeof AppGroupsGroupIdRoute
    }
  }
}

interface AppGroupsGroupIdRouteChildren {
  AppGroupsGroupIdInsightsRoute: typeof AppGroupsGroupIdInsightsRoute
  AppGroupsGroupIdIndexRoute: typeof AppGroupsGroupIdIndexRoute
  AppGroupsGroupIdExpensesNewRoute: typeof AppGroupsGroupIdExpensesNewRoute
}

const AppGroupsGroupIdRouteChildren: AppGroupsGroupIdRouteChildren = {
  AppGroupsGroupIdInsightsRoute: AppGroupsGroupIdInsightsRoute,
  AppGroupsGroupIdIndexRoute: AppGroupsGroupIdIndexRoute,
  AppGroupsGroupIdExpensesNewRoute: AppGroupsGroupIdExpensesNewRoute,
}

const AppGroupsGroupIdRouteWithChildren =
  AppGroupsGroupIdRoute._addFileChildren(AppGroupsGroupIdRouteChildren)

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppPersonalRoute: typeof AppPersonalRoute
  AppFriendsFriendIdRoute: typeof AppFriendsFriendIdRoute
  AppGroupsGroupIdRoute: typeof AppGroupsGroupIdRouteWithChildren
  AppGroupsNewRoute: typeof AppGroupsNewRoute
  AppFriendsIndexRoute: typeof AppFriendsIndexRoute
  AppGroupsIndexRoute: typeof AppGroupsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppPersonalRoute: AppPersonalRoute,
  AppFriendsFriendIdRoute: AppFriendsFriendIdRoute,
  AppGroupsGroupIdRoute: AppGroupsGroupIdRouteWithChildren,
  AppGroupsNewRoute: AppGroupsNewRoute,
  AppFriendsIndexRoute: AppFriendsIndexRoute,
  AppGroupsIndexRoute: AppGroupsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  SettingsRoute: SettingsRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
